language: rust
os: linux
dist: focal
addons:
  apt:
    # sources:
      # - deb http://archive.ubuntu.com/ubuntu hirsute universe
    packages:
      - autoconf
      # - lua5.3
      # - liblua5.3-dev
      - luarocks
      - m4
      - python3-pip
      # - lua5.3 # This should be lua5.4, but this is yet available on a travis-supported Ubuntu (requires >= hirsute)
      # - liblua5.3-dev # This should be liblua5.4-0, but this is yet available on a travis-supported Ubuntu (requires >= hirsute)
# services:
  # - docker
# archlinux:
  # # repos:
  # # - papyros=http://dash.papyros.io/repos/$repo/$arch
  # packages:
    # # - papyros-shell
    # - glibc
    # - gcc
    # - libcss
    # - libsass
    # - lua
    # - lua-argparse
    # - lua-htmlparser
    # - lua-lyaml
    # - moonscript
    # - ncurses
    # - python
    # - rust
    # - yq
  # mount:
    # - ~/.pkg-cache:/var/cache/pacman/pkg
  # # before_install:
    # # - "sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook"
  # script:
    # - make doc
    # - mdbook build && mdbook test
cache:
  - cargo
  - pip
  - "~/.local/bin"
rust:
  - stable
before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu hirsute universe"
  - sudo apt install lua5.4 liblua5.4-dev
  - sudo chown -R $(whoami) /usr/local
  - luarocks install moonscript
  - luarocks install argparse
  - luarocks install lyaml
  - luarocks install luafilesystem
  - pip3 install --upgrade pip
  - pip3 install jq yq
  - 'export PATH=$PATH:~/.local/bin'
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a
script:
  - ./scripts/autogen -v
  # - ./configure
  # - make
  - ./scripts/docgen -v
  - mdbook build docs/ # && mdbook test docs/
deploy:
  # - provider: releases # Deploy to latest release
    # api_key: ...
    # file:
      # - README.md
      # - em.1.gz
      # - em
    # skip_cleanup: true
    # on:
      # tags: true
  - provider: pages # Deploy documentation
    strategy: git
    edge: true
    cleanup: false
    github_token: $GITHUB_TOKEN
    local_dir: docs/book
    keep_history: false
    # on:
      # branch: master
    target_branch: gh-pages
