#include "html.h"

#include "data/cmp.h"
#include "data/hash.h"
#include "data/list.h"
#include "data/map.h"
#include "data/str.h"
#include "driver-util.h"
#include "linear-formatter.h"
#include "logs/logs.h"
#include "write-out.h"
#include <errno.h>
#include <string.h>
#include <unistd.h>

static Pair const html_special_functions[] = {
	{ "h1", "h1" },
	{ "h2", "h2" },
	{ "h3", "h3" },
	{ "h4", "h4" },
	{ "h5", "h5" },
	{ "h6", "h6" },
	{ "h1*", "h1" },
	{ "h2*", "h2" },
	{ "h3*", "h3" },
	{ "h4*", "h4" },
	{ "h5*", "h5" },
	{ "h6*", "h6" },
};
static const size_t num_html_special_functions = sizeof(html_special_functions) / sizeof(*html_special_functions);

static int driver_runner(Doc* doc, DriverParams* params);
static int output_stylesheet(LinearFormatter* formatter, Str* time_str, List* css_snippets);
static int format_doc_as_html(LinearFormatter* formatter, Str* time_str, Doc* doc);
static int format_node_as_html(LinearFormatter* formatter, DocTreeNode* node);
static int format_node_list_as_html(LinearFormatter* formatter, List* node_list);

#define HTML_HEADER                                                                                                    \
	"<!DOCTYPE html>\n"                                                                                                \
	"<!-- This file was generated by `em` on %s. -->\n"                                                                \
	"<!-- Any changes will be overwritten next time typesetting is run -->\n"
#define STYLESHEET_HEADER                                                                                              \
	"/*\n"                                                                                                             \
	" * This file was generated by `em` on %s.\n"                                                                      \
	" * Any changes will be overwritten next time typesetting is run.\n"                                               \
	" */\n"
#define STYLESHEET_LINK				  "<link rel=\"stylesheet\" type=\"text/css\" href=\"%s\">"
#define TITLE_DEF					  "<title>%s</title>"
#define HTML_DOCUMENT_OUTPUT_NAME_FMT "%s.html"

int make_html_driver(InternalDriver* driver)
{
	OutputDriverInf* driver_inf = malloc(sizeof(OutputDriverInf));
	driver_inf->support			= TS_BASIC_STYLING,

	driver->name = "html";
	driver->inf	 = driver_inf;
	driver->run	 = driver_runner;

	return 0;
}

static int driver_runner(Doc* doc, DriverParams* params)
{
	int rc;
	LinearFormatter formatter;
	Str document_output_name_fmt;
	make_strv(&document_output_name_fmt, HTML_DOCUMENT_OUTPUT_NAME_FMT);
	make_linear_formatter(
		&formatter, params, num_html_special_functions, html_special_functions, &document_output_name_fmt);
	Str time_str;
	get_time_str(&time_str);

	log_info("Outputting document to '%s'", formatter.output_doc_name->str);

	// Reformat the document and output it
	rc = format_doc_as_html(&formatter, &time_str, doc);
	if (rc)
		return rc;
	rc = write_linear_formatter_output(&formatter);
	if (rc)
		return rc;

	// Output the style file
	rc = output_stylesheet(&formatter, &time_str, doc->styler->snippets);
	if (rc)
		return rc;

	dest_linear_formatter(&formatter);
	return 0;
}

static int format_doc_as_html(LinearFormatter* formatter, Str* time_str, Doc* doc)
{
	append_linear_formatter_strf(formatter, HTML_HEADER, time_str->str);
	append_linear_formatter_raw(formatter, "<html>");
	append_linear_formatter_raw(formatter, "\n<head>\n");
	append_linear_formatter_strf(formatter, STYLESHEET_LINK, formatter->stylesheet_name->str);
	append_linear_formatter_strf(formatter, TITLE_DEF, formatter->output_doc_name->str);
	/* append_linear_formatter_raw(formatter, "<meta name=\"theme-color\" content=\"#2d2d2d\"/>"); */
	append_linear_formatter_raw(formatter, "\n</head>");
	append_linear_formatter_raw(formatter, "\n<body>\n");
	int rc = format_node_as_html(formatter, doc->root);
	if (rc)
		return rc;
	append_linear_formatter_raw(formatter, "\n</body>");
	append_linear_formatter_raw(formatter, "\n</html>");

	return 0;
}

static int format_node_as_html(LinearFormatter* formatter, DocTreeNode* node)
{
	switch (node->content->type)
	{
		case WORD:
		{
			append_linear_formatter_raw(formatter, " ");
			ListNode* ln = malloc(sizeof(ListNode));
			make_list_node(ln, node->content->word);
			append_list_node(formatter->content, ln);
			return 0;
		}
		case CALL:
		{
			Str* html_node_name;
			Maybe m;
			get_map(&m, formatter->call_name_map, node->name);
			switch (m.type)
			{
				case JUST:
					html_node_name = m.just;
					break;
				case NOTHING:
					html_node_name = malloc(sizeof(Str));
					make_strv(html_node_name, "span");
					ListNode* ln = malloc(sizeof(ListNode));
					make_list_node(ln, html_node_name);
					append_list_node(formatter->formatter_content, ln);
					break;
				default:
					log_err("Maybe object has unknown data constructor: %d", m.type);
					return 1;
			}
			int rc = 0;
			if (node->content->call_params->result)
			{
				append_linear_formatter_strf(formatter, "<%s class=\"%s\">", html_node_name->str, node->name->str);
				rc = format_node_as_html(formatter, node->content->call_params->result);
				append_linear_formatter_strf(formatter, "</%s>", html_node_name->str);
			}
			dest_maybe(&m, NULL);
			return rc;
		}
		case LINE:
			return format_node_list_as_html(formatter, node->content->line);
		case LINES:
			return format_node_list_as_html(formatter, node->content->lines);
		case PAR:
			append_linear_formatter_raw(formatter, "<p>");
			int rc = format_node_list_as_html(formatter, node->content->par);
			append_linear_formatter_raw(formatter, "</p>");
			return rc;
		case PARS:
			return format_node_list_as_html(formatter, node->content->pars);
		default:
			log_err("Unknown node content type: %d", node->content->type);
			return 1;
	}
}

static int format_node_list_as_html(LinearFormatter* formatter, List* node_list)
{
	int rc = 0;

	ListIter li;
	make_list_iter(&li, node_list);
	DocTreeNode* node;
	while (iter_list((void**)&node, &li))
	{
		rc = format_node_as_html(formatter, node);
		if (rc)
			break;
	}
	dest_list_iter(&li);
	return rc;
}

static int output_stylesheet(LinearFormatter* formatter, Str* time_str, List* css_snippets)
{
	log_info("Outputting stylesheet to '%s'", formatter->stylesheet_name->str);

	// Add the header to the css
	ListNode* ln		 = malloc(sizeof(ListNode));
	size_t header_len	 = 1 + snprintf(NULL, 0, STYLESHEET_HEADER, time_str->str);
	char* header_content = malloc(header_len);
	snprintf(header_content, header_len, STYLESHEET_HEADER, time_str->str);
	Str* header_str = malloc(sizeof(Str));
	make_strr(header_str, header_content);
	make_list_node(ln, header_str);
	prepend_list_node(css_snippets, ln);

	return write_output(formatter->stylesheet_name, css_snippets);
}
