[package]
name = "yuescript_src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.79"
mlua = { version = "0.8.8", features = [ "luajit52", "vendored" ] }
