#!/bin/bash

set -e

mkdir -p ./docs/man/man1
(./scripts/mangen | gzip - -) < em.yml > ./docs/man/man1/$(yq -y .program em.yml | head -n 1).1.gz

doxygen ./docs/Doxyfile
breathe-apidoc -fq -p emblem -o ./docs/rst/ ./docs/xml/
sassc < ./docs/_static/css/style.scss > ./docs/_static/css/style.css
sphinx-build -WqaEn --keep-going -c ./docs/ ./docs/ ./docs/html/
