#!/bin/bash

set -e

core_srcs=($(find src/ -name '*.c' -or -name '*.h'))
lib_srcs=($(find src/ext/lib -name '*.moon' | grep -v '__mod'))

mkdir docs/src/generated/

./scripts/docs/SUMMARY
moon ./scripts/docs/cli-api-gen > docs/src/generated/command-line-args.md
moon ./scripts/docs/code-to-md-doc ${core_srcs[@]} ${lib_srcs[@]}

mdbook build docs/
