#!/bin/bash

set -e

function module-name()
{
	( sed 's/src\/ext\/lib\///' \
	| sed 's/.moon$//' \
	| sed 's/\//./g'
	) < /dev/stdin
}

if [[ $# -ge 1 ]]; then
	echo $@ | module-name
else
	module-name
fi
