#!/bin/bash

set -e

if [[ $# -lt 2 ]]; then
	echo "$0 usage:\n$0 INPUT.moon OUTPUT" >&2
	exit 1
elif [[ $# -gt 2 ]]; then
	echo "$0 has been passed more than two arguments" >&2
	exit 1
fi

input=$1
output=$2
loc_map_output=${input%%.moon}.loc

intermediate_moon_mod_file=${input%%.moon}__mod.moon
intermediate_lua_file=${input%%.moon}.lua
module_name=$(./scripts/module_name $input)

moonc -l $input
awk -f scripts/moon-module-make.awk -v module_name="$module_name" < "$input" > "$intermediate_moon_mod_file"
moonc -- < $intermediate_moon_mod_file > $intermediate_lua_file
moonc -X $input | awk '{r=0}{ for (i=1;i<NF;i++) { t=match($i, /^[0-9]+:\[$/); if (t) { if (r) printf " "; r=1; printf "%s", $i; } } } r { print "" }' | sed 's/:\[//g' > "$loc_map_output"
(luac -o - $intermediate_lua_file | ./scripts/bin2c.lua /dev/stdin "$module_name") > "$output"
